### ISSUE TITLE
Help me complete and organize the README

### ISSUE THREAD

**Issue by raniesantos** [mikerockett/vue-routisan#46]
See recent commits in `dev` branch.

There are a bunch of incomplete sections and examples in the README.

Also, I feel like the README has been getting messy as I've added more to it so I could use some help with that.

You just need to be familiar with how vue-router and Laravel's router work.

___

If you decide to help with this, I might ask you to be the 2nd maintainer of this package.

This is just a small repo that isn't very busy. It's functionality is also very specific so it won't grow into some huge plugin, so if you're interested please step forward.

**Comment by mikerockett** [comment]
Closing as the readme is in the process of being revamped as part of the next release (not scheduled yet).
